# Generated by Django 4.1.3 on 2022-12-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_appointment_doctor_alter_patient_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
