# Generated by Django 4.1.3 on 2022-12-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_remove_doctor_duration_remove_doctor_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointmentdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointmenttime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_email',
            new_name='patientemail',
        ),
    ]
